# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=800)),
                ('notes', models.TextField(blank=True, max_length=2048, verbose_name='Administrator notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('state', models.CharField(choices=[('submitted', 'submitted'), ('verified', 'verified'), ('notified', 'notified'), ('handled', 'handled')], default='submitted', max_length=9)),
            ],
        ),
    ]
